"""add new picture schema

Revision ID: 0ad7a5fadfb2
Revises: 1f9152cb2520
Create Date: 2024-06-21 13:24:59.976719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad7a5fadfb2'
down_revision = '1f9152cb2520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.BLOB(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['picture'])
        batch_op.create_foreign_key(None, 'pictures', ['picture'], ['id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.BLOB(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['picture'])
        batch_op.create_foreign_key(None, 'pictures', ['picture'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('picture',
               existing_type=sa.Integer(),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('picture',
               existing_type=sa.Integer(),
               type_=sa.BLOB(),
               existing_nullable=True)

    op.drop_table('pictures')
    # ### end Alembic commands ###
