"""Add cascade deletes and restructure relationships

Revision ID: 1b8fd52637ce
Revises: 
Create Date: 2024-11-20 16:25:48.574497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8fd52637ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_services_picture', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_services_picture_id'), ['picture_id'])
        batch_op.drop_constraint('fk_services_picture_pictures', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_services_picture_id_pictures'), 'pictures', ['picture_id'], ['id'])
        batch_op.drop_column('picture')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_vehicles_picture', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_vehicles_picture_id'), ['picture_id'])
        batch_op.drop_constraint('fk_vehicles_picture_pictures', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vehicles_picture_id_pictures'), 'pictures', ['picture_id'], ['id'])
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_vehicles_picture_id_pictures'), type_='foreignkey')
        batch_op.create_foreign_key('fk_vehicles_picture_pictures', 'pictures', ['picture'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_vehicles_picture_id'), type_='unique')
        batch_op.create_unique_constraint('uq_vehicles_picture', ['picture'])
        batch_op.drop_column('picture_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_services_picture_id_pictures'), type_='foreignkey')
        batch_op.create_foreign_key('fk_services_picture_pictures', 'pictures', ['picture'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_services_picture_id'), type_='unique')
        batch_op.create_unique_constraint('uq_services_picture', ['picture'])
        batch_op.drop_column('picture_id')

    # ### end Alembic commands ###
