"""empty message

Revision ID: 24a912e605b2
Revises: 0d6c9c7c8290
Create Date: 2024-05-08 10:14:34.633822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a912e605b2'
down_revision = '0d6c9c7c8290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
